cask "atom"
brew "nmap"
brew "node"
brew "htop"
cask "iterm2"
cask "java"
cask "vlc"
cask "ngrok"
cask "skype"
cask "sublime-text"
cask "google-chrome"
cask "dropbox"
mas "Xcode", id: 497799835
